### PR TITLE
Add method to create a DSN without defaults

### PR DESCRIPTION
**Pull request by srmor**
Creates a method that allows one to make a DSN without any defaults set. Back compatible since it's a new method that shares the DSN creation code with the Datasource method.

### CODE REVIEW

**Comment by lestrrat** [comment]
@srmor 

1. tests are failing
2. I think this is the other way around: You should create a new method that has the new semantics, and keep the old name alone
3. Any parameter that can be passed as its Zero value can safely be changed to use the Option pattern to save typing, so when you make a new method, you should probably do that.

**Comment by srmor** [comment]
hmmm I'm really not exactly clear on what you are meaning by 2 and 3 @lestrrat. I thought you didn't want to change the current method because that would break back-compatibility...

**Comment by lestrrat** [comment]
Please see @033c7aa for what I meant. If it looks OK, I will open a new PR for it.

**Comment by srmor** [comment]
That works for me @lestrrat

**Comment by lestrrat** [comment]
Cool! merged

**Comment by lestrrat** [comment]
@srmor ...And README has been updated

**Comment by srmor** [comment]
Thanks @lestrrat!

**Pull request closed without merging**
